### ISSUE TITLE
helm repo add pulls old version

### ISSUE THREAD

**Issue by kicsiperez** [iits-consulting/otc-prometheus-exporter#43]
Hi!
as i can see you have refactored a lot of things 3 weeks ago, but when i use the command from the readme 
helm repo add otc-prometheus-exporter https://iits-consulting.github.io/otc-prometheus-exporter/
and then i try it with a dry run debug
helm install --dry-run --debug otc-prometheus-exporter otc-prometheus-exporter/otc-prometheus-exporter
the deployment.yaml looks like the one from older versions like in the other branches other than the main.

should i use some other url?

thanks for the help in advance

**Comment by erjondibraniiits** [comment]
Hello,
thank you for your question. I will release it now under ´v0.5.0´. If this doesn't solve your issue feel free to ask us.
Best regards!

**Comment by kicsiperez** [comment]
thanks, it is good now
