### ISSUE TITLE
[VPC] getPublicIpIdNameMapping use wrong vpcClient.ResourceBase

### ISSUE THREAD

**Issue by ckroehnert** [iits-consulting/otc-prometheus-exporter#56]
getPublicIpIdNameMapping override the vpcClient.ResourceBase from openstack.NewNetworkV1 instead to append the project ID.

so instead of calling:
https://vpc.eu-de.otc.t-systems.com/v1/{project_id}/publicips
will be called:
https://vpc.eu-de.otc.t-systems.com/{project_id}/publicips

**Comment by zeljkobekcic** [comment]
Good catch, I must have overseen this. I commented on your PR. Just posting this comment to make sure you see it :)

**Comment by ckroehnert** [comment]
Exists already a planed release date with latest changes?

**Comment by zeljkobekcic** [comment]
I will create a patch release now :)

**Comment by zeljkobekcic** [comment]
I just created a new realease, `v0.6.1`. You should be able to just update the version.

**Comment by ckroehnert** [comment]
Thank you. I will test it next week.

**Comment by ckroehnert** [comment]
The new version works for us. Thank you.
